package modelo;
// Generated 23-jun-2017 11:41:28 by Hibernate Tools 4.3.1



/**
 * Estudios generated by hbm2java
 */
public class Estudios  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private String estudios;

    public Estudios() {
    }

	
    public Estudios(Paciente paciente) {
        this.paciente = paciente;
    }
    public Estudios(Paciente paciente, String estudios) {
       this.paciente = paciente;
       this.estudios = estudios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getEstudios() {
        return this.estudios;
    }
    
    public void setEstudios(String estudios) {
        this.estudios = estudios;
    }




}


