package modelo;
// Generated 23-jun-2017 11:41:28 by Hibernate Tools 4.3.1



/**
 * FichaMedica generated by hbm2java
 */
public class FichaMedica  implements java.io.Serializable {


     private Integer idapp;
     private Paciente paciente;
     private String app;
     private String cirugiaprevia;
     private Boolean transfucion = false;
     private Boolean alergias = false;
     private String descalergia;
     private String antecefamiliar;
     private String motivoconsulta;
     private String antecenfernedad;
     private String examenfisico;
     private String efpa;
     private String efsat;
     private String effc;
     private String eftemp;
     private String estudiosolicitado;
     private String imprediagnostico;
     private String tratamiento;

    public FichaMedica() {
    }

	
    public FichaMedica(Paciente paciente) {
        this.paciente = paciente;
    }
    public FichaMedica(Paciente paciente, String app, String cirugiaprevia, Boolean transfucion, Boolean alergias, String descalergia, String antecefamiliar, String motivoconsulta, String antecenfernedad, String examenfisico, String efpa, String efsat, String effc, String eftemp, String estudiosolicitado, String imprediagnostico, String tratamiento) {
       this.paciente = paciente;
       this.app = app;
       this.cirugiaprevia = cirugiaprevia;
       this.transfucion = transfucion;
       this.alergias = alergias;
       this.descalergia = descalergia;
       this.antecefamiliar = antecefamiliar;
       this.motivoconsulta = motivoconsulta;
       this.antecenfernedad = antecenfernedad;
       this.examenfisico = examenfisico;
       this.efpa = efpa;
       this.efsat = efsat;
       this.effc = effc;
       this.eftemp = eftemp;
       this.estudiosolicitado = estudiosolicitado;
       this.imprediagnostico = imprediagnostico;
       this.tratamiento = tratamiento;
    }
   
    public Integer getIdapp() {
        return this.idapp;
    }
    
    public void setIdapp(Integer idapp) {
        this.idapp = idapp;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getCirugiaprevia() {
        return this.cirugiaprevia;
    }
    
    public void setCirugiaprevia(String cirugiaprevia) {
        this.cirugiaprevia = cirugiaprevia;
    }
    public Boolean getTransfucion() {
        return this.transfucion;
    }
    
    public void setTransfucion(Boolean transfucion) {
        this.transfucion = transfucion;
    }
    public Boolean getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(Boolean alergias) {
        this.alergias = alergias;
    }
    public String getDescalergia() {
        return this.descalergia;
    }
    
    public void setDescalergia(String descalergia) {
        this.descalergia = descalergia;
    }
    public String getAntecefamiliar() {
        return this.antecefamiliar;
    }
    
    public void setAntecefamiliar(String antecefamiliar) {
        this.antecefamiliar = antecefamiliar;
    }
    public String getMotivoconsulta() {
        return this.motivoconsulta;
    }
    
    public void setMotivoconsulta(String motivoconsulta) {
        this.motivoconsulta = motivoconsulta;
    }
    public String getAntecenfernedad() {
        return this.antecenfernedad;
    }
    
    public void setAntecenfernedad(String antecenfernedad) {
        this.antecenfernedad = antecenfernedad;
    }
    public String getExamenfisico() {
        return this.examenfisico;
    }
    
    public void setExamenfisico(String examenfisico) {
        this.examenfisico = examenfisico;
    }
    public String getEfpa() {
        return this.efpa;
    }
    
    public void setEfpa(String efpa) {
        this.efpa = efpa;
    }
    public String getEfsat() {
        return this.efsat;
    }
    
    public void setEfsat(String efsat) {
        this.efsat = efsat;
    }
    public String getEffc() {
        return this.effc;
    }
    
    public void setEffc(String effc) {
        this.effc = effc;
    }
    public String getEftemp() {
        return this.eftemp;
    }
    
    public void setEftemp(String eftemp) {
        this.eftemp = eftemp;
    }
    public String getEstudiosolicitado() {
        return this.estudiosolicitado;
    }
    
    public void setEstudiosolicitado(String estudiosolicitado) {
        this.estudiosolicitado = estudiosolicitado;
    }
    public String getImprediagnostico() {
        return this.imprediagnostico;
    }
    
    public void setImprediagnostico(String imprediagnostico) {
        this.imprediagnostico = imprediagnostico;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }




}


