package modelo;
// Generated 23-jun-2017 11:41:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private Integer documento;
     private String nombre;
     private String apellido;
     private Date fechanac;
     private String tel;
     private String cel;
     private Set fichaMedicas = new HashSet(0);
     private Set estudioses = new HashSet(0);
     private Set seguimientos = new HashSet(0);

    public Paciente() {
    }

    public Paciente(Integer documento, String nombre, String apellido, Date fechanac, String tel, String cel, Set fichaMedicas, Set estudioses, Set seguimientos) {
       this.documento = documento;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechanac = fechanac;
       this.tel = tel;
       this.cel = cel;
       this.fichaMedicas = fichaMedicas;
       this.estudioses = estudioses;
       this.seguimientos = seguimientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Integer documento) {
        this.documento = documento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechanac() {
        return this.fechanac;
    }
    
    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getCel() {
        return this.cel;
    }
    
    public void setCel(String cel) {
        this.cel = cel;
    }
    public Set getFichaMedicas() {
        return this.fichaMedicas;
    }
    
    public void setFichaMedicas(Set fichaMedicas) {
        this.fichaMedicas = fichaMedicas;
    }
    public Set getEstudioses() {
        return this.estudioses;
    }
    
    public void setEstudioses(Set estudioses) {
        this.estudioses = estudioses;
    }
    public Set getSeguimientos() {
        return this.seguimientos;
    }
    
    public void setSeguimientos(Set seguimientos) {
        this.seguimientos = seguimientos;
    }




}


